### ISSUE TITLE
Cannot use ConceptMap or $translate - OMOPonFHIR (OMOPv5/FHIR STU3) - 4.2.0

### ISSUE THREAD

**Issue by salvolpe** [omoponfhir/omoponfhir-main#10]
Based on my understanding of how OMOP on FHIR has been presented to OHDSI, we should be able to use certain aspects of Terminology Servers, such as looking through ConceptMaps and using the $translate operation. However, upon review of the Conformance Statement and resources in the provided UI, it does not seem like any of these have been fleshed out.

Does the new version of OMOP on FHIR with OMOPv6 and R4 address this? If not, will this be implemented in later versions or do you have any means by which to implement these on my own end after installation?

**Comment by salvolpe** [comment]
Yes I saw that in the conformance statement but it gave me a [GET] not defined error, which I did not receive when trying to run a $translate call in the public HAPI FHIR server. 

But I also noticed that there was no instances listed next to ConceptMap on the main UI page. Does that mean that I would have to manually load-in the all of the mappings? Because I see all of the functionality in the Java and structure for all the different coding systems in the omop_v5 Postgres schema. I have not tried posting any of my own ConceptMap resources to the server yet

**Comment by myungchoi** [comment]
ConceptMap has not yet been implemented. It's there to have $translate operation. ConceptMap can be implemented using OMOP's concept and concept relationship table. We will need to do this. But, we have another higher priority work to do. If you are welcomed to do this if you wish to do this. 

For $translate operation, I found one error, which was caused by last update we made on OMOP version. I fixed it and pushed to repo. 

http://localhost:8080/fhir/ConceptMap/$translate?system=http://www.nlm.nih.gov/research/umls/rxnorm&code=311040&targetsystem=http://hl7.org/fhir/ndfrt

This will produce the following output. 
```
{
  "resourceType": "Parameters",
  "parameter": [
    {
      "name": "result",
      "valueBoolean": true
    },
    {
      "name": "match",
      "part": [
        {
          "name": "equivalence",
          "valueCode": "equivalent"
        },
        {
          "name": "concept",
          "valueCoding": {
            "system": "http://hl7.org/fhir/ndfrt",
            "code": "4014955",
            "display": "INSULIN,ASPART,HUMAN 100 UNT/ML INJ"
          }
        }
      ]
    }
  ]
}
```

**Comment by salvolpe** [comment]
When I ran `http://localhost:8080/omoponfhir4/fhir/ConceptMap/$translate?system=http://www.nlm.nih.gov/research/umls/rxnorm&code=311040&targetsystem=http://hl7.org/fhir/ndfrt`
I got the following response:
```
HTTP 500 Internal Server Error
{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Failed to call access method: java.lang.IllegalArgumentException: Unable to locate Attribute  with the the given name [concept1] on this ManagedType [unknown]</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "Failed to call access method: java.lang.IllegalArgumentException: Unable to locate Attribute  with the the given name [concept1] on this ManagedType [unknown]"
    }
  ]
}
```

**Comment by salvolpe** [comment]
Resolved by most recent commit to the repo
