### ISSUE TITLE
Issues with POST Condition

### ISSUE THREAD

**Issue by hms1** [omoponfhir/omoponfhir-main#15]
First of all thank you so much for your work on this. I have managed to get things running and successfully POST a FHIR Patient resource and have it mapped to OMOP.

However I am having difficulties with POST of other types of resource, for example Condition, which are all failing with error:

``` json
"issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "Failed to call access method: org.springframework.orm.jpa.JpaSystemException: org.hibernate.exception.ConstraintViolationException: could not execute batch; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute batch"
        }
]
```
This looks like an error writing to the DB?

I've tried all sorts of Condition resources both extensive and pared back, for example:

``` json
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "Failed to call access method: org.springframework.orm.jpa.JpaSystemException: org.hibernate.exception.ConstraintViolationException: could not execute batch; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute batch"
        }
    ]
```

Any pointers or how to debug further would be much appreciated!

**Comment by navndn** [comment]
Hi @hms1 Were you able to figure out the cause for this issue? Did you face this issue while creating any other resource like medRequest, encounter, Observation?  I'm facing this issue for all resources except Patient. 
Thanks
