### ISSUE TITLE
MedicationStatement FHIR required fields

### ISSUE THREAD

**Issue by eric-chou** [omoponfhir/omoponfhir-main#4]
Hello,
Thank you again for your work on this project! It has worked very smoothly in providing FHIR resources for our data, but one thing that we were wondering about is that it appears that under the [FHIR STU3 specification](https://hl7.org/fhir/STU3/medicationstatement.html), the "status" element is not provided when OMOP on FHIR renders the resources for specific dataset. This may become an issue for us since some of the FHIR applications we hope to work with may check for airtight conformance to the STU3 standard, and a missing "required" field such as [MedicationStatementStatus](https://hl7.org/fhir/STU3/valueset-medication-statement-status.html) could be an obstacle. Thus, we were wondering if there was anything that might be missing in our data that is resulting in this field not being available, or if something else needs to be introduced in the data or in the codebase.

An example of this should be able to be seen at [this URL](http://ec2-3-16-159-252.us-east-2.compute.amazonaws.com/omoponfhir-stu3/fhir/MedicationStatement/160023) (a screenshot of this resource is at the bottom in case this doesn't load). All of our MedicationStatement resources are available [here](http://ec2-3-16-159-252.us-east-2.compute.amazonaws.com/omoponfhir-stu3/tester/search?serverId=home&pretty=true&resource=MedicationStatement&param.0.qualifier=&param.0.0=&param.0.1=&param.0.name=_id&param.0.type=token&sort_by=&sort_direction=&resource-search-limit=).

![image](https://user-images.githubusercontent.com/9423731/73197065-b58cdd00-40fe-11ea-9514-0b355ae5af31.png)

**Comment by myungchoi** [comment]
The status is fixed on Nov 2019: 
https://github.com/omoponfhir/omoponfhir-omopv5-stu3-mapping/commit/b85802ffcbf18c98a01be4818b289d097c6c31bc

Please see constructFHIR method in OmopMedicationStatement.java

If you update yours, the status will show up. If OMOP drug exposure has stop reason populated, then the status will be changed to stopped and reason is added to note. Otherwise, status is set to active.
