### ISSUE TITLE
Having problems with Authorization Header

### ISSUE THREAD

**Issue by eric-chou** [omoponfhir/omoponfhir-main#5]
Hello,

Recently I pulled a lot of changes to the most recent master branch after running on version 1.0.0 for awhile, but now I am running into an ```HTTP 401 : No or Invalid Authorization Header``` whenever I try to find resources in the "tester" interface which appears to originate from [OIDCInterceptor.java](https://github.com/omoponfhir/omoponfhir-stu3-server/blob/21d106dea0f7426dcb2b2dc7c87a8bc80fccd354/src/main/java/edu/gatech/chai/omoponfhir/security/OIDCInterceptor.java). I attached a .txt file that should include the full log file output of the error message. Is there an additional configuration step or something that I may have missed?

![image](https://user-images.githubusercontent.com/9423731/74672478-5c531f00-517b-11ea-990c-9c4494233c4d.png)

Retrieving raw resources via the API's "omoponfhir/fhir/..." url works smoothly, as command line inputs such as ```curl  -H 'Authorization: Basic Y2xpZW50X29tb3A6c2VjcmV0' 'http://localhost:8080/omoponfhir-stu3/fhir/Patient/1539'```, but I haven't been able to get the UI to work.

Thank you for your time!

[error.txt](https://github.com/omoponfhir/omoponfhir-main/files/4214995/error.txt)

**Comment by myungchoi** [comment]
I haven't documented this yet. I just updated the readme file with environment file. Please set environment variables for AUTH_BASIC (or AUTH_BEARER if you want). The tester will use these environment variable and set its header. Tester UI is a client app, which needs to know this information. 

The authorization is to support SMART on FHIR support, which the omoponfhir-stu3-server now includes for simple OAUTH2 with scopes functionality.

**Comment by eric-chou** [comment]
Awesome the documentation is very helpful, thank you!
