### ISSUE TITLE
Missing files when downloading source code from http://omoponfhir.org/

### ISSUE THREAD

**Issue by ericpan64** [omoponfhir/omoponfhir-main#7]
The "Download .zip" and "Download .tar.gz" options from [omoponfhir.org](omoponfhir.org) save the following folders with _no_ files in them: 

- omoponfhir-omopv5-jpabase
- omoponfhir-omopv5-stu3-mapping
- omoponfhir-stu3-server

This is likely because this repo uses links to the repository names above which doesn't get picked-up in the HTML reference URLs:
`        <a href="https://github.com/omoponfhir/omoponfhir-main/zipball/master" class="btn">Download .zip</a>`
`        <a href="https://github.com/omoponfhir/omoponfhir-main/tarball/master" class="btn">Download .tar.gz</a>`

**Comment by myungchoi** [comment]
github's download sources do not include the submodules. Removed the links to download sources from the page. Source codes can now only be downloaded from repositories.
