### ISSUE TITLE
Error 404 on http://localhost:8080/omoponfhir

### ISSUE THREAD

**Issue by salvolpe** [omoponfhir/omoponfhir-main#8]
I just tried setting up an omoponfhir instance on my desktop using the README from this omoponfhir-main and linking it to the smart-postgres SQL database that I forked from [the link provided in the README](https://github.com/omoponfhir/omopv5fhir-pgsql/). I can get the Tomcat to open at `localhost:8080`, but `http://localhost:8080/omoponfhir3` throws an Error 404.

Here is what my Dockerfile looks like:
```
#Build the Maven project
FROM maven:3.6.1-alpine as builder
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN mvn clean install

#Build the Tomcat container
FROM tomcat:alpine
#set environment variables below and uncomment the line. Or, you can manually set your environment on your server.
ENV JDBC_URL=jdbc:postgresql://omopv5fhir-pgsql:5432/smart-postgres?currentSchema=omop_v5 JDBC_USERNAME=smart-postgres JDBC_PASSWORD=i3lworks
RUN apk update
RUN apk add zip postgresql-client

# Copy GT-FHIR war file to webapps.
COPY --from=builder /usr/src/app/omoponfhir-stu3-server/target/omoponfhir-stu3-server.war $CATALINA_HOME/webapps/omoponfhir3.war

EXPOSE 8080
```

I don't know if I'm not typing something correctly into one of the environment variables or if I have to change things in my `docker-compose.yml` file. I'm not sure. This is my first time working with Docker containers.

Do you have any thoughts?

**Comment by salvolpe** [comment]
The URL issue was a typo. I actually tried it with `http://localhost:8080/omoponfhir3/` and the other prefab URLs and they do not work.

I am completely unfamiliar with Docker. Would you explain in a general sense how I would go about setting up the communication? I have the desktop version and CLI-tools for Docker

**Comment by myungchoi** [comment]
Please post here the output of “sudo docker ps -a” here. We can see what you have there and status of docker containers. We can go from there.

**Comment by salvolpe** [comment]
Sorry to leave you hanging @myungchoi . I tried to resolve the issue by attaching `smart-postgres` to the `omoponfhir-main_default` bridge that comes with the installation and that didn't solve the problem. Here is the output of my `sudo` call:

```
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                   PORTS                    NAMES
ad6ca8813ebd        omoponfhir-main_omoponfhir   "catalina.sh run"        13 days ago         Up 44 hours              0.0.0.0:8080->8080/tcp   omoponfhir-main_omoponfhir_1
338cdf426eef        smart-postgres:latest        "docker-entrypoint.s…"   2 weeks ago         Up 10 minutes            0.0.0.0:5432->5432/tcp   smart-postgres
2b9724195181        docker/getting-started       "/docker-entrypoint.…"   2 weeks ago         Exited (0) 13 days ago                            funny_kirch
```

**Comment by salvolpe** [comment]
@myungchoi Any thoughts on these?

**Comment by salvolpe** [comment]
This issue has been resolved!

In case anyone else has similar issues, here is what worked for me:

## Modifying variables when using the omopv5fhir-pgsql instructions

Your ENV variables should be updated as such

```
ENV JDBC_URL=jdbc:postgresql://smart-postgres:5432/postgres?currentSchema=omop_v5 JDBC_USERNAME=omop_v5 JDBC_PASSWORD=i3lworks
```

- Breaking down the variables
  - JDBC_URL=jdbc:<dbclient>://<container-name>:<port-number>/<dbclient-command-form>?currentSchema=<POSTGRES_DB>
  - For currentSchema, JDBC_USERNAME, JDBC_PASSWORD look in the Dockerfile for `omopv5fhir-pgsql`
    - currentSchema, after POSTGRES_DB
    - JDBC_USERNAME, after POSTGRES_USER
    - JDBC_PASSWORD, after POSTGRES_PASSWORD
